name: poke_guess
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  cloud_firestore: ^4.12.0
  firebase_auth: ^4.11.1
  firebase_core: ^2.19.0
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.8
  http: ^0.13.3
  searchfield: ^0.8.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/witp.jpg
  fonts:
    - family: Pokemon
      fonts:
        - asset: fonts/Pokemon-Solid.ttf
    - family: PokemonGb
      fonts:
        - asset: fonts/PokemonGb-RAeo.ttf
